[project]
name = "1010s"
version = "0.1.0"
description = "CS1010S Programming Methodology assignments"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cocos2d>=0.6.10",
    "pillow>=11.3.0",
    "seaborn>=0.13.2",
]
